name: Run tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2.4.1
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test


  Run-Lint:
    runs-on: ubuntu-latest
    name: TypeScript static analysis
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2.4.1
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint


  Slither-Analyzer:
    runs-on: ubuntu-latest
    name: Solidity static analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Slither Static Analysis
        uses: luisfontes19/slither-static-analysis-action@v0.3.4
        with:
          slither-params: '--filter-paths "BitDAO.sol|contracts/treasury|node_modules"'
          cache: 'npm'
